spring: 
  datasource:
    url: jdbc:mysql://139.159.210.42:3306/sell?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: MyNewPassword4!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: false
  redis:
    host: 139.159.210.42
    port: 6379
    password: foobared123!@#
logging:
  level:
    org.springframework.web: error
    com.imooc.sell: error
    com.imooc.sell.dataobject.mapper: trace
server:
  port: 8080
wechat:
  key-path: /Users/wangyanjun/workspace/sell/src/main/resources/cert/h5.p12