spring:
  profiles:
    active:
    - dev
  jackson:
    default-property-inclusion: non_null
  freemarker: 
    allow-request-override: false
    allow-session-override: false
    cache: false
    checkTemplateLocation: true
    content-type: text/html
    exposeRequestAttributes: false
    exposeSessionAttributes: false
    exposeSpringMacroHelpers: false
    prefer-file-system-access: true
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates/
server:
  context-path: /sell
  error:
    path: /error
  session: 
    timeout: 5000
  tomcat:
    max-threads: 80000
    uri-encoding: UTF-8
wechat: 
  mp:
    mpAppId: wx53762126******** #土豆互联公众号AppId
    mpAppSecret: 15b6fcb9cd933a********3e708f040a #土豆互联公众号AppSecret
    ##  mpAppId: wxe6b15040e8fe0a5d #测试号AppId
    ##  mpAppSecret: 747700f306a528059fb4aa73cb917340 #测试号AppSecret
    mchId: 14********
    mchKey: c6b8341c4d274189bee934********12
    token: potato369token
    aesKey: 8XSi84XgQJ1NE2Hh01FIzJxRVxUq7Eg********nq62
    notifyUrl: /pay/notify
    templateId:
      orderStatus: l8ZgiVk7Cb3art8XjHtsyv6uPrpooT3********ywLM
      orderSuccess: Z_y_ovpCRyU0eBrikdJL9_VsehJA_Ao********8vgc
      paySuccess: oFx8eJFfs8VC_x58KflhSRcsLBgxCp0y1********Rc
  open: 
    openAppid: wx3c2ae2********21
    openAppSecret: 0a355cb0843b9b21f9c********a72e5

projectUrl: 
  projectName: /sell
  domainUrl: http://potato369.mynatapp.cc
  wechatMpAuthorizeUrl: /wechat/authorize
  wechatMpAuthorizeUrlUserInfo: /wechat/userInfo
  wechatOpenAuthorizeUrl: /wechat/qrAuthorize
  wechatOpenAuthorizeUrlUserInfo: /wechat/qrUserInfo
  loginUrl: /seller/login
  logoutUrl: /seller/logout
  errorUrl: /error
  successUrl: /success
mybatis:
  mapper-locations: classpath:mapper/*