spring: 
  datasource:
    url: jdbc:mysql://114.**.**.**:3306/sell?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: My******
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  redis:
    host: 139.**.**.**
    port: 6379
    password: fo******123!**
logging:
  level:
    org.springframework.web: info
    com.imooc.sell: info
    com.imooc.sell.dataobject.mapper: trace
server:
  port: 8080
wechat:
  key-path: /workspace/sell/src/main/resources/cert/h5.p12